<?php

namespace FondOfSpryker\Zed\Availability\Business\Model;

use Spryker\Zed\Availability\Business\Model\AvailabilityHandler as BaseAvailabilityHandler;
use Spryker\Zed\Availability\Business\Model\SellableInterface;
use Spryker\Zed\Availability\Dependency\Facade\AvailabilityToProductInterface;
use Spryker\Zed\Availability\Dependency\Facade\AvailabilityToStockInterface;
use Spryker\Zed\Availability\Dependency\Facade\AvailabilityToTouchInterface;
use Spryker\Zed\Availability\Persistence\AvailabilityQueryContainerInterface;

class AvailabilityHandler extends BaseAvailabilityHandler
{
    protected $defaultMinQty;

    /**
     * @param \Spryker\Zed\Availability\Business\Model\SellableInterface $sellable
     * @param \Spryker\Zed\Availability\Dependency\Facade\AvailabilityToStockInterface $stockFacade
     * @param \Spryker\Zed\Availability\Dependency\Facade\AvailabilityToTouchInterface $touchFacade
     * @param \Spryker\Zed\Availability\Persistence\AvailabilityQueryContainerInterface $queryContainer
     * @param \Spryker\Zed\Availability\Dependency\Facade\AvailabilityToProductInterface $productFacade
     * @param float $defaultMinQty
     */
    public function __construct(
        SellableInterface $sellable,
        AvailabilityToStockInterface $stockFacade,
        AvailabilityToTouchInterface $touchFacade,
        AvailabilityQueryContainerInterface $queryContainer,
        AvailabilityToProductInterface $productFacade,
        float $defaultMinQty
    ) {
        parent::__construct($sellable, $stockFacade, $touchFacade, $queryContainer, $productFacade);

        $this->defaultMinQty = $defaultMinQty;
    }

    /**
     * @param string $sku
     * @param int $quantity
     *
     * @return \Orm\Zed\Availability\Persistence\SpyAvailability
     */
    protected function saveAndTouchAvailability($sku, $quantity)
    {
        $quantity = $quantity - $this->defaultMinQty;

        if ($quantity < 0) {
            $quantity = 0;
        }

        return parent::saveAndTouchAvailability($sku, $quantity); // TODO: Change the autogenerated stub
    }
}
